global using Chat.Bi.SharedKernel;
global using Chat.Bi.SharedKernel.Cqrs.Interfaces;
global using Chat.Bi.Core.Repositories;
global using Chat.Bi.Core.Services;
global using Chat.Bi.Infrastructure.Persistence;
global using Chat.Bi.SharedKernel.Extensions;
global using Chat.Bi.Core.Entities;
global using Chat.Bi.Application.ViewModels;
global using Chat.Bi.SharedKernel.Common;